### ISSUE TITLE
Keybind

### ISSUE THREAD

**Issue by 3kh0** [Murka007/Dsync-client#1]
What keybind do you use to start the client

**Comment by Murka007** [comment]
It is tampermonkey script, you can download it on greasyfork https://greasyfork.org/en/scripts/449995-dsync-client-sploop-io

**Comment by Murka007** [comment]
It is tampermonkey script, you can download it on greasyfork https://greasyfork.org/en/scripts/449995-dsync-client-sploop-io
Script will be automatically executed in the game

**Comment by 3kh0** [comment]
ok thanks!
