### ISSUE TITLE
doesn't work when ran as a bookmark 

### ISSUE THREAD

**Issue by imightknoiw** [Murka007/Dsync-client#2]
i copied everything from `Function` to `();` but it doesn't load the script.
can you make it work for bookmarks?
the reason I want this is because tampermonkey is blocked on my computer.
i have seen other players use this script and its pretty good so keep it up!

**Comment by Murka007** [comment]
You can execute a code using another extensions, such as: **requestly** or **resource override**. Just make sure that the code loaded as fast as possible.
